### ISSUE TITLE
Web IDE needs filename collision validation.

### ISSUE THREAD

**Issue by meawoppl** [spark/spark.github.io#2]
There are a couple of permutations of "bad things" you can do through the web IDE at the moment the general formulate:
-- Add a new file named [file-name-x].h (creates file-name-x.cpp and file-name-x.h)
-- Remove [file-name-x].h
-- Add [file-name-x].h (multiple file-name-x.cpp now exists)

Deleting either file-name-x.h removes both, and editing either and reloading leads to unpredictable behavior.

**Comment by zsup** [comment]
I believe this was fixed some time ago, so I'm going to close this issue, but @joegoggins let me know if that's incorrect
