### ISSUE TITLE
Link to Mocha is invalid

### ISSUE THREAD

**Issue by smmathews** [spark/spark.github.io#3]
Under the 'Contributions' section, the link to the mocha testing framework is currently 'http://visionmedia.github.io/mocha/', which gives a '404 not found' error message. Perhaps spark meant to link to 'https://github.com/mochajs/mocha'?

**Comment by zsup** [comment]
Fixed with this commit:

https://github.com/spark/spark.github.io/commit/67939d85032538354d390cfa55195cb4b3ddd765
