### ISSUE TITLE
Typo in setup.partilc.io

### ISSUE THREAD

**Issue by ScruffR** [spark/spark.github.io#8]
Since I can't find a better repo to report this to and more and more people seem to experience this, I'll open this here

 https://community.particle.io/t/cannot-connect-electron-using-3rd-party-sim-so-net-in-japan/21338/3
 https://community.particle.io/t/electron-particle-sim-u260-u270-confusion-in-au-unable-to-activate/21184/11
 https://community.particle.io/t/cant-download-the-3rd-party-sim-binary-for-electron/20251/36

All report a typo in 
```
ElectronActions.js:243 OPTIONS https://api.particle.i/v1/binaries net::ERR_NAME_NOT_RESOLVED
```
The `o` in `api.particle.io` seems to be missing.

**Comment by monkbroc** [comment]
Thanks @ScruffR. I'll file a companion issue on the appropriate internal repository.

**Comment by idokleinman** [comment]
Checking..

**Comment by brycekahle** [comment]
FYI this would be a great thing to file on the new `cloud` repo at https://github.com/spark/cloud

**Comment by idokleinman** [comment]
Found bug, fixed. Thanks for reporting.

**Comment by ScruffR** [comment]
@brycekahle, I see. 
Since I still use the Open Source link in the forum, having a "hub" for this repo there would be good too.
In exchange the core-common-lib or core-communication-lib hubs could die ;-)

**Comment by idokleinman** [comment]
@brycekahle not a cloud bug. WDS app was removing the last letter from (the new) particle-api-js base URL (it previously had a /)
